services:
  - type: web
    name: bookmyseat
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn bookmyseat.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
